/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/finance/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Słownik walut wraz z liczbą miejsc po przecinku */
        get: operations["listCurrencies"];
        put?: never;
        /** Dodanie waluty do słownika */
        post: operations["addCurrency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kursy waluty w zakresie dat */
        get: operations["listExchangeRates"];
        put?: never;
        /**
         * Ręczny wpis kursu
         * @description Zapisany kurs dostaje źródło `MANUAL`. Ponowny wpis na tę samą datę nadpisuje poprzedni.
         */
        post: operations["addExchangeRate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/exchange-rates/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pobranie kursów z NBP za zakres dat
         * @description Tabela A NBP. Waluta bazowa jest pomijana — jej kurs z definicji wynosi 1. Dni bez publikacji (weekendy, święta) po prostu nie mają wpisu.
         */
        post: operations["syncExchangeRates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista kont */
        get: operations["listAccounts"];
        put?: never;
        /** Nowe konto */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Zmiana danych konta */
        put: operations["updateAccount"];
        post?: never;
        /**
         * Archiwizacja konta
         * @description Konto nie znika — historia transakcji musi zostać. Zarchiwizowane konto przestaje się pojawiać na listach wyboru.
         */
        delete: operations["archiveAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saldo konta w jego walucie i w walucie bazowej
         * @description Saldo liczy się zapytaniem, nie jest przechowywane. Wartość w walucie bazowej przelicza się kursem **bieżącym** — to stan majątku na dziś, w odróżnieniu od transakcji, które trzymają kurs historyczny.
         */
        get: operations["getAccountBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Drzewo kategorii
         * @description Zwraca korzenie; podkategorie siedzą w polu `children`.
         */
        get: operations["listCategories"];
        put?: never;
        /** Nowa kategoria lub podkategoria */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Zmiana kategorii */
        put: operations["updateCategory"];
        post?: never;
        /**
         * Archiwizacja kategorii
         * @description Kategoria zostaje w bazie razem z podkategoriami — inaczej historyczne transakcje straciłyby przypisanie.
         */
        delete: operations["archiveCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transakcje z filtrami i stronicowaniem */
        get: operations["searchTransactions"];
        put?: never;
        /**
         * Nowa transakcja
         * @description Kwota jest zawsze dodatnia — kierunek wynika z pola `type`. Kurs i kwota w walucie bazowej wyliczają się przy zapisie i już się nie zmieniają.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/finance/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pojedyncza transakcja */
        get: operations["getTransaction"];
        /**
         * Zmiana transakcji
         * @description Kurs jest wyznaczany od nowa dla daty księgowania po zmianie — inaczej przesunięcie daty zostawiłoby kwotę bazową policzoną dla starej.
         */
        put: operations["updateTransaction"];
        post?: never;
        /** Usunięcie transakcji */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Kod maszynowy — po nim klient rozpoznaje przypadek, nie po treści
             * @example CURRENCY_MISMATCH
             * @example TRANSFER_WITHOUT_TARGET
             * @example EXCHANGE_RATE_NOT_FOUND
             */
            errorCode: string;
            message: string;
            /** Format: date-time */
            timestamp: string;
            traceId?: string | null;
        };
        /** @enum {string} */
        AccountType: "BANK" | "CASH" | "CARD";
        /** @enum {string} */
        CategoryDirection: "EXPENSE" | "INCOME";
        /** @enum {string} */
        TransactionType: "EXPENSE" | "INCOME" | "TRANSFER";
        /** @enum {string} */
        RateSource: "NBP" | "MANUAL";
        /** @description Waluta słownikowa; `minorUnit` decyduje o formatowaniu kwot. */
        CurrencyResponse: {
            /** @example PLN */
            code: string;
            name: string;
            /**
             * Format: int32
             * @description Liczba miejsc po przecinku — PLN 2, JPY 0, TND 3
             */
            minorUnit: number;
        };
        CurrencyRequest: {
            code: string;
            name: string;
            /** Format: int32 */
            minorUnit: number;
        };
        ExchangeRateResponse: {
            code: string;
            /** Format: date */
            rateDate: string;
            /**
             * @description Ile waluty bazowej za jednostkę tej waluty; dziesiętnie, jako tekst
             * @example 4.32150000
             */
            rate: string;
            source: components["schemas"]["RateSource"];
        };
        ExchangeRateRequest: {
            code: string;
            /** Format: date */
            rateDate: string;
            /** @example 4.32150000 */
            rate: string;
        };
        SyncExchangeRatesRequest: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @description Puste = wszystkie waluty ze słownika poza bazową */
            codes?: string[];
        };
        SyncExchangeRatesResponse: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /**
             * Format: int32
             * @description Liczba zapisanych kursów; dni bez publikacji NBP nie mają wpisu
             */
            savedCount: number;
            codes: string[];
        };
        AccountRequest: {
            name: string;
            type: components["schemas"]["AccountType"];
            currency: string;
            iban?: string | null;
            /**
             * Format: int64
             * @description Saldo otwarcia w jednostkach podrzędnych waluty konta
             */
            openingBalanceMinor: number;
            /** Format: date */
            openingBalanceOn: string;
        };
        AccountResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            type: components["schemas"]["AccountType"];
            /** @description Skalę tej waluty klient bierze ze słownika `/currencies` */
            currency: string;
            iban?: string | null;
            /** Format: int64 */
            openingBalanceMinor: number;
            /** Format: date */
            openingBalanceOn: string;
            archived: boolean;
        };
        AccountBalanceResponse: {
            /** Format: int64 */
            accountId: number;
            currency: string;
            /** Format: int32 */
            minorUnit: number;
            /**
             * Format: int64
             * @description Saldo w walucie konta; ujemne jest dopuszczalne
             */
            balanceMinor: number;
            baseCurrency: string;
            /**
             * Format: int64
             * @description Saldo przeliczone kursem bieżącym na walutę bazową
             */
            baseBalanceMinor: number;
            fxRate: string;
            /** Format: date */
            fxRateDate: string;
        };
        CategoryRequest: {
            /** Format: int64 */
            parentId?: number | null;
            name: string;
            direction: components["schemas"]["CategoryDirection"];
        };
        CategoryResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            parentId?: number | null;
            name: string;
            direction: components["schemas"]["CategoryDirection"];
            archived: boolean;
            children: components["schemas"]["CategoryResponse"][];
        };
        /** @description `TRANSFER` wymaga `toAccountId` i nie przyjmuje `categoryId`; `EXPENSE` i `INCOME` odwrotnie. `toAmountMinor` jest wymagane, gdy konta transferu mają różne waluty. */
        TransactionRequest: {
            type: components["schemas"]["TransactionType"];
            /** Format: date */
            bookedOn: string;
            /**
             * Format: int64
             * @description Zawsze dodatnia — kierunek wynika z `type`
             */
            amountMinor: number;
            currency: string;
            /** Format: int64 */
            originalAmountMinor?: number | null;
            originalCurrency?: string | null;
            /** Format: int64 */
            accountId: number;
            /** Format: int64 */
            toAccountId?: number | null;
            /** Format: int64 */
            toAmountMinor?: number | null;
            /** Format: int64 */
            categoryId?: number | null;
            description?: string | null;
            counterparty?: string | null;
        };
        TransactionResponse: {
            /** Format: int64 */
            id: number;
            type: components["schemas"]["TransactionType"];
            /** Format: date */
            bookedOn: string;
            /** Format: int64 */
            amountMinor: number;
            currency: string;
            /** Format: int64 */
            baseAmountMinor: number;
            baseCurrency: string;
            fxRate: string;
            /**
             * Format: date
             * @description Data faktycznie użytego kursu — bywa wcześniejsza niż `bookedOn`, bo NBP nie publikuje tabel w weekendy i święta
             */
            fxRateDate: string;
            /** Format: int64 */
            originalAmountMinor?: number | null;
            originalCurrency?: string | null;
            /** Format: int64 */
            accountId: number;
            accountName: string;
            /** Format: int64 */
            toAccountId?: number | null;
            toAccountName?: string | null;
            /** Format: int64 */
            toAmountMinor?: number | null;
            /** Format: int64 */
            categoryId?: number | null;
            categoryName?: string | null;
            description?: string | null;
            counterparty?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        TransactionPageResponse: {
            content: components["schemas"]["TransactionResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
    };
    responses: {
        /** @description Błąd walidacji */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Zasób nie istnieje */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Konflikt z istniejącym stanem */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Zewnętrzne API niedostępne */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Id: number;
        /** @description Początek zakresu dat, włącznie */
        From: string;
        /** @description Koniec zakresu dat, włącznie */
        To: string;
        /** @description Domyślnie zarchiwizowane pozycje są pomijane */
        IncludeArchived: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waluty posortowane po kodzie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyResponse"][];
                };
            };
        };
    };
    addCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrencyRequest"];
            };
        };
        responses: {
            /** @description Waluta dodana */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    listExchangeRates: {
        parameters: {
            query: {
                /** @description Kod waluty, np. `EUR` */
                code: string;
                /** @description Początek zakresu dat, włącznie */
                from?: components["parameters"]["From"];
                /** @description Koniec zakresu dat, włącznie */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kursy rosnąco po dacie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateResponse"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    addExchangeRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRateRequest"];
            };
        };
        responses: {
            /** @description Kurs zapisany */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    syncExchangeRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncExchangeRatesRequest"];
            };
        };
        responses: {
            /** @description Podsumowanie synchronizacji */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncExchangeRatesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["BadGateway"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                /** @description Domyślnie zarchiwizowane pozycje są pomijane */
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Konta posortowane po nazwie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        responses: {
            /** @description Konto utworzone */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        responses: {
            /** @description Konto po zmianie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Konto zarchiwizowane */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAccountBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saldo konta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalanceResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                /** @description Ogranicza drzewo do kategorii wydatkowych albo przychodowych */
                direction?: components["schemas"]["CategoryDirection"];
                /** @description Domyślnie zarchiwizowane pozycje są pomijane */
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kategorie najwyższego poziomu z podkategoriami */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Kategoria utworzona */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Kategoria po zmianie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    archiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kategoria zarchiwizowana */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    searchTransactions: {
        parameters: {
            query?: {
                /** @description Początek zakresu dat, włącznie */
                from?: components["parameters"]["From"];
                /** @description Koniec zakresu dat, włącznie */
                to?: components["parameters"]["To"];
                /** @description Konto źródłowe albo docelowe transferu */
                accountId?: number;
                categoryId?: number;
                type?: components["schemas"]["TransactionType"];
                currency?: string;
                page?: number;
                /** @description Maksymalnie 100 — większa wartość jest przycinana */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strona transakcji, najnowsze pierwsze */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description Transakcja zapisana */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transakcja */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description Transakcja po zmianie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transakcja usunięta */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
