/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/kitchen/api/v1/dictionaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Komplet słowników do formularza i filtrów
         * @description Formularz przepisu potrzebuje wszystkich słowników naraz, a zmieniają się
         *     rzadko — stąd jedno wywołanie zamiast sześciu. Puste listy są poprawną
         *     odpowiedzią: znaczą, że słownik jeszcze nie ma pozycji.
         */
        get: operations["dictionaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Komplet słowników potrzebnych formularzowi przepisu i filtrom */
        DictionariesResponse: {
            units?: components["schemas"]["UnitResponse"][];
            cuisines?: components["schemas"]["DictionaryEntryResponse"][];
            categories?: components["schemas"]["DictionaryEntryResponse"][];
            diets?: components["schemas"]["DictionaryEntryResponse"][];
            tags?: components["schemas"]["DictionaryEntryResponse"][];
            equipment?: components["schemas"]["DictionaryEntryResponse"][];
        };
        /** @description Pozycja słownika: kuchnia, kategoria, dieta, tag albo sprzęt */
        DictionaryEntryResponse: {
            /** Format: int64 */
            id?: number;
            /** @example polska */
            name?: string;
        };
        /** @description Jednostka miary ze słownika */
        UnitResponse: {
            /** Format: int64 */
            id?: number;
            /** @example lyzka */
            code?: string;
            /** @example łyżka */
            name?: string;
            kind?: components["schemas"]["UnitKind"];
        };
        /**
         * @description Rodzaj jednostki. Przeliczać wolno wyłącznie w obrębie jednego rodzaju —
         *     zamiana gramów na mililitry zależy od produktu i nie należy do słownika.
         * @enum {string}
         */
        UnitKind: "MASS" | "VOLUME" | "COUNT" | "OTHER";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dictionaries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Słowniki */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionariesResponse"];
                };
            };
        };
    };
}
