/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wyszukiwarka katalogu z filtrami, sortowaniem i stronicowaniem */
        get: operations["searchTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/tracks/{spotifyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pojedynczy utwór z katalogu */
        get: operations["getTrack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/tracks/{spotifyId}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metryki wgrane z pliku (D24) */
        get: operations["getTrackMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/metrics-coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ile utworów katalogu ma metryki z pliku */
        get: operations["getMetricsCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strona wpisów bibliotecznych */
        get: operations["listLibraryTracks"];
        put?: never;
        /** Ręczne dodanie utworu do biblioteki */
        post: operations["addLibraryTrack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/tracks/{spotifyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLibraryTrack"];
        put?: never;
        post?: never;
        /** Usunięcie wpisu; katalog zostaje bez zmian */
        delete: operations["deleteLibraryTrack"];
        options?: never;
        head?: never;
        /**
         * Zmiana danych prywatnych DJ-a
         * @description Pole pominięte zostaje bez zmian; pusta wartość czyści pole.
         *     `version` jest wymagana (D29) — nieświeża kończy się 409.
         */
        patch: operations["updateLibraryTrack"];
        trace?: never;
    };
    "/api/library/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Przegląd biblioteki — rozkłady liczone w bazie (D27) */
        get: operations["getLibraryOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tagi użyte w bibliotece */
        get: operations["listLibraryTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlaylists"];
        put?: never;
        post: operations["createPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlaylist"];
        put?: never;
        post?: never;
        delete: operations["deletePlaylist"];
        options?: never;
        head?: never;
        patch: operations["renamePlaylist"];
        trace?: never;
    };
    "/api/playlists/{id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Nowa kolejność — musi być permutacją obecnego składu */
        put: operations["reorderPlaylist"];
        /** Dokłada utwór na koniec setu */
        post: operations["addPlaylistTrack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}/tracks/{spotifyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Usuwa utwór i zwiera pozycje pozostałych */
        delete: operations["removePlaylistTrack"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}/export-to-spotify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pierwszy eksport zakłada playlistę, kolejny nadpisuje tę samą */
        post: operations["exportPlaylistToSpotify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propozycja setu z puli kandydatów; nic nie zapisuje */
        post: operations["proposeSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{playlistId}/fill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Uzupełnia gotowy set do zadanego czasu */
        post: operations["fillSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{playlistId}/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dobiera kandydatów na wskazane miejsce w secie */
        post: operations["suggestForSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Startuje job wzbogacania (asynchronicznie) */
        post: operations["startEnrichment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ile utworów obejmie zlecenie i ile to będzie kosztowało */
        post: operations["estimateEnrichment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEnrichJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/jobs/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEnrichJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/jobs/{executionId}/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Utwory pominięte w przebiegu wraz z powodem (D37) */
        get: operations["getEnrichJobFailures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/jobs/{executionId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart nieudanego wykonania — dokańcza od checkpointu */
        post: operations["restartEnrichJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/missing-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Braki per grupa pól */
        get: operations["getMissingCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import utworów z pliku CSV */
        post: operations["ingestFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import metryk z jednego lub wielu plików (D24) */
        post: operations["ingestMetrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/playlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import playlisty ze Spotify spod linku */
        post: operations["ingestPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/my-playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import wszystkich playlist połączonego konta
         * @description Awaria pojedynczej playlisty nie przerywa przebiegu.
         */
        post: operations["ingestMyPlaylists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/my-playlists/refresh-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wynik ostatniego cyklicznego odświeżenia playlist */
        get: operations["getPlaylistRefreshStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/spotify/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Przekierowanie do zgody OAuth Spotify */
        get: operations["spotifyLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/spotify/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Odbiór kodu autoryzacyjnego */
        get: operations["spotifyCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/spotify/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Czy konto Spotify jest połączone */
        get: operations["spotifyStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        GenreFamily: "LATIN" | "ROCK" | "POP" | "DISCO" | "DISCO_POLO" | "ELECTRONIC" | "HIP_HOP" | "OTHER";
        /** @enum {string} */
        TempoClass: "SLOW" | "MEDIUM" | "FAST" | "VERY_FAST";
        /** @enum {string} */
        BpmSource: "MANUAL" | "ACOUSTICBRAINZ" | "DEEZER" | "LLM";
        /** @enum {string} */
        MissingGroup: "METADATA" | "AUDIO" | "AI" | "ANY";
        /** @enum {string} */
        CatalogSort: "RELEVANCE" | "TITLE" | "ARTIST" | "ALBUM" | "YEAR" | "BPM" | "POPULARITY" | "DURATION" | "DANCEABILITY" | "ENERGY" | "RATING" | "ADDED_AT";
        /** @enum {string} */
        SortDirection: "ASC" | "DESC";
        /** @enum {string} */
        EnrichmentScope: "SINGLE" | "SELECTED" | "MISSING" | "OUTDATED";
        /** @enum {string} */
        FieldGroup: "METADATA" | "AUDIO" | "AI";
        /** @enum {string} */
        SetCurve: "STANDARD" | "WEDDING" | "CLUB" | "EVEN";
        /** @enum {string} */
        DjSlot: "WARMUP" | "MIDDLE" | "PEAK" | "CLOSING" | "BREAK";
        /** @enum {string} */
        LibrarySource: "FILE" | "PLAYLIST" | "FOREIGN_PLAYLIST";
        /**
         * @description Wynik ostatniego cyklicznego odświeżenia playlist. SKIPPED_NOT_CONNECTED
         *     to normalny stan świeżej instalacji, nie awaria.
         * @enum {string}
         */
        RefreshOutcome: "NEVER_RUN" | "DISABLED" | "SKIPPED_NOT_CONNECTED" | "REFRESHED" | "FAILED";
        ErrorResponse: {
            /** @example TRACK_NOT_FOUND */
            errorCode: string;
            message: string;
            /** Format: date-time */
            timestamp: string;
            traceId: string | null;
        };
        TrackResponse: {
            spotifyId: string;
            title: string | null;
            artist: string | null;
            album: string | null;
            /** Format: int32 */
            year: number | null;
            /** Format: int32 */
            durationMs: number | null;
            /** Format: int32 */
            popularity: number | null;
            explicit: boolean | null;
            albumImageUrl: string | null;
            isrc: string | null;
            genreFamily: string | null;
            style: string | null;
            /** Format: int32 */
            bpm: number | null;
            bpmSource: string | null;
            danceability: number | null;
            musicalKey: string | null;
            /** @description Liczona z `musicalKey` przez backend (D25) — nie kolumna w bazie */
            camelot: string | null;
            tempoClass: string | null;
            energy: string | null;
            lyricsTheme: string | null;
            descriptionPl: string | null;
            confidence: string | null;
            /** Format: date-time */
            enrichedAt: string | null;
            modelUsed: string | null;
            /** Format: int32 */
            enrichVersion: number | null;
        };
        TrackLibraryResponse: {
            /** Format: int32 */
            rating: number | null;
            customTags: string[] | null;
            /** Format: date-time */
            addedAt: string;
            source: string;
        };
        CatalogRowResponse: {
            track: components["schemas"]["TrackResponse"];
            library: components["schemas"]["TrackLibraryResponse"] | null;
        };
        PageCatalogRowResponse: {
            content: components["schemas"]["CatalogRowResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageLibraryEntryResponse: {
            content: components["schemas"]["LibraryEntryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        TrackMetricsResponse: {
            spotifyId: string;
            bpm: number | null;
            musicalKey: string | null;
            camelot: string | null;
            danceability: number | null;
            energy: number | null;
            valence: number | null;
            acousticness: number | null;
            instrumentalness: number | null;
            speechiness: number | null;
            liveness: number | null;
            loudnessDb: number | null;
            /** Format: int32 */
            timeSignature: number | null;
            source: string | null;
            /** Format: date-time */
            importedAt: string;
        };
        MetricsCoverageResponse: {
            /** Format: int64 */
            withMetrics: number;
            /** Format: int64 */
            total: number;
        };
        LibraryEntryResponse: {
            /** Format: int64 */
            id: number;
            spotifyId: string;
            source: string;
            /** Format: date-time */
            addedAt: string;
            djNotes: string | null;
            customTags: string[] | null;
            /** Format: int32 */
            rating: number | null;
            djSlotOverride: string | null;
            /** Format: int32 */
            version: number;
            track: components["schemas"]["TrackResponse"];
        };
        AddLibraryTrackRequest: {
            spotifyId: string;
            title: string;
            artist: string;
            album?: string | null;
        };
        /** @description Pole pominięte zostaje bez zmian; pusta wartość czyści pole. */
        UpdateLibraryEntryRequest: {
            djNotes?: string | null;
            customTags?: string[] | null;
            /**
             * Format: int32
             * @description 0 czyści ocenę; poza tym dozwolone 1–5
             */
            rating?: number | null;
            djSlotOverride?: string | null;
            /** Format: int32 */
            version: number;
        };
        BucketResponse: {
            label: string;
            /** Format: int64 */
            count: number;
        };
        MatrixCellResponse: {
            tempoClass: string;
            energy: string;
            /** Format: int64 */
            count: number;
        };
        MetricResponse: {
            label: string;
            value: number;
        };
        RecentTrackResponse: {
            spotifyId: string;
            title: string | null;
            artist: string | null;
            albumImageUrl: string | null;
            /** Format: date-time */
            addedAt: string;
        };
        ScaleResponse: {
            /** Format: int64 */
            catalogTracks: number;
            /** Format: int64 */
            libraryTracks: number;
            /** Format: int64 */
            tracksWithMetrics: number;
            /** Format: int64 */
            libraryDurationMs: number;
            /** Format: int64 */
            distinctArtists: number;
            /** Format: int64 */
            distinctAlbums: number;
            averageBpm: number | null;
            averageDurationMs: number | null;
            averagePopularity: number | null;
            averageDanceability: number | null;
            /** Format: int64 */
            tracksWithDanceability: number;
        };
        QualityResponse: {
            /** Format: int64 */
            metadataMissing: number;
            /** Format: int64 */
            audioMissing: number;
            /** Format: int64 */
            aiMissing: number;
            bpmSources: components["schemas"]["BucketResponse"][];
            confidences: components["schemas"]["BucketResponse"][];
        };
        SoundResponse: {
            genres: components["schemas"]["BucketResponse"][];
            styles: components["schemas"]["BucketResponse"][];
            tempoClasses: components["schemas"]["BucketResponse"][];
            energies: components["schemas"]["BucketResponse"][];
            bpmHistogram: components["schemas"]["BucketResponse"][];
            camelotKeys: components["schemas"]["BucketResponse"][];
            durations: components["schemas"]["BucketResponse"][];
            popularity: components["schemas"]["BucketResponse"][];
            explicitness: components["schemas"]["BucketResponse"][];
            timeSignatures: components["schemas"]["BucketResponse"][];
            tempoEnergy: components["schemas"]["MatrixCellResponse"][];
            audioProfile: components["schemas"]["MetricResponse"][];
        };
        TimelineResponse: {
            monthlyGrowth: components["schemas"]["BucketResponse"][];
            decades: components["schemas"]["BucketResponse"][];
        };
        TasteResponse: {
            topArtists: components["schemas"]["BucketResponse"][];
            topAlbums: components["schemas"]["BucketResponse"][];
            topTags: components["schemas"]["BucketResponse"][];
            ratings: components["schemas"]["BucketResponse"][];
        };
        LibraryOverviewResponse: {
            scale: components["schemas"]["ScaleResponse"];
            quality: components["schemas"]["QualityResponse"];
            sound: components["schemas"]["SoundResponse"];
            timeline: components["schemas"]["TimelineResponse"];
            taste: components["schemas"]["TasteResponse"];
            recentlyAdded: components["schemas"]["RecentTrackResponse"][];
        };
        PlaylistSummaryResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            spotifyPlaylistId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            trackCount: number;
            /** Format: int32 */
            version: number;
        };
        PlaylistTrackResponse: {
            /** Format: int32 */
            position: number;
            djSlot: string | null;
            djSlotOverride: string | null;
            metrics: components["schemas"]["TrackMetricsResponse"] | null;
            track: components["schemas"]["TrackResponse"];
        };
        PlaylistResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            spotifyPlaylistId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            version: number;
            tracks: components["schemas"]["PlaylistTrackResponse"][];
        };
        SavePlaylistRequest: {
            name: string;
            /**
             * Format: int32
             * @description Wymagana przy zmianie nazwy (D29); pomijana przy tworzeniu
             */
            version?: number | null;
        };
        AddPlaylistTrackRequest: {
            spotifyId: string;
        };
        ReorderPlaylistRequest: {
            spotifyIds: string[];
            /** Format: int32 */
            version: number;
        };
        PlaylistExportResponse: {
            /** Format: int64 */
            playlistId: number;
            spotifyPlaylistId: string;
            name: string;
            /** Format: int32 */
            exportedTracks: number;
            /** @description true — playlista założona, false — nadpisana */
            created: boolean;
            spotifyUrl: string;
        };
        /** @description Filtry puli kandydatów, wspólne dla propozycji, uzupełniania i dobierania. */
        SetFilters: {
            search?: string | null;
            genreFamily?: string | null;
            /** Format: int32 */
            bpmMin?: number | null;
            /** Format: int32 */
            bpmMax?: number | null;
            tempoClass?: string | null;
            energy?: string | null;
            inLibrary?: boolean | null;
            /** Format: int32 */
            ratingMin?: number | null;
            tag?: string | null;
            camelot?: string | null;
            camelotCompatible?: boolean | null;
            valenceMin?: number | null;
            valenceMax?: number | null;
            instrumentalMin?: number | null;
            livenessMax?: number | null;
        };
        SetProposalRequest: components["schemas"]["SetFilters"] & {
            /** Format: int32 */
            targetMinutes: number;
            curve?: string | null;
            /** Format: int64 */
            seed?: number | null;
        };
        SetFillRequest: components["schemas"]["SetFilters"] & {
            /** Format: int32 */
            targetMinutes: number;
            curve?: string | null;
            /** Format: int64 */
            seed?: number | null;
        };
        SetSuggestionRequest: components["schemas"]["SetFilters"] & {
            /**
             * Format: int32
             * @description Brak wartości znaczy „na koniec setu"
             */
            position?: number | null;
            /** Format: int32 */
            limit?: number | null;
        };
        ProposedTrackResponse: {
            /** Format: int32 */
            position: number;
            djSlot: string | null;
            track: components["schemas"]["TrackResponse"];
        };
        SetProposalResponse: {
            /** Format: int32 */
            trackCount: number;
            /** Format: int64 */
            totalDurationMs: number;
            /** Format: int64 */
            targetDurationMs: number;
            /** Format: int64 */
            seed: number;
            notes: string[];
            tracks: components["schemas"]["ProposedTrackResponse"][];
        };
        SetFillResponse: {
            /** Format: int32 */
            currentTrackCount: number;
            /** Format: int64 */
            currentDurationMs: number;
            /** Format: int32 */
            addedTrackCount: number;
            /** Format: int64 */
            totalDurationMs: number;
            /** Format: int64 */
            targetDurationMs: number;
            /** Format: int64 */
            seed: number;
            notes: string[];
            tracks: components["schemas"]["ProposedTrackResponse"][];
        };
        SuggestedTrackResponse: {
            djSlot: string | null;
            /** Format: int32 */
            bpmDelta: number | null;
            harmonic: boolean | null;
            track: components["schemas"]["TrackResponse"];
        };
        SetSuggestionResponse: {
            /** Format: int32 */
            position: number;
            suggestions: components["schemas"]["SuggestedTrackResponse"][];
        };
        EnrichRequest: {
            scope: components["schemas"]["EnrichmentScope"];
            fields: components["schemas"]["FieldGroup"][];
            /** @description Wymagane dla SINGLE i SELECTED, zabronione dla MISSING i OUTDATED */
            spotifyIds?: string[] | null;
        };
        ExecutionIdResponse: {
            /** Format: int64 */
            executionId: number;
        };
        EnrichmentEstimateResponse: {
            /** Format: int64 */
            trackCount: number;
            /**
             * Format: int64
             * @description Utwory idące do LLM-a — sufit liczy się po nich, nie po przebiegu
             */
            aiTracks: number;
            /** @description Pusty, gdy w konfiguracji nie ma stawek providera */
            estimatedCost: number | null;
            /** Format: int32 */
            limit: number;
            withinLimit: boolean;
        };
        EnrichJobResponse: {
            /** Format: int64 */
            executionId: number;
            /** Format: int64 */
            jobInstanceId: number;
            status: string;
            scope: string | null;
            fields: string | null;
            /** Format: int64 */
            readCount: number;
            /** Format: int64 */
            writeCount: number;
            /** Format: int64 */
            failedCount: number;
            /** Format: date-time */
            startTime: string | null;
            /** Format: date-time */
            endTime: string | null;
            exitDescription: string | null;
        };
        EnrichFailureResponse: {
            spotifyId: string;
            reason: string;
            /** Format: date-time */
            failedAt: string;
        };
        MissingFieldsCount: {
            /** Format: int64 */
            metadata: number;
            /** Format: int64 */
            audio: number;
            /** Format: int64 */
            ai: number;
        };
        RowErrorResponse: {
            /** Format: int64 */
            line: number;
            reason: string;
        };
        IngestFileResponse: {
            /** Format: int32 */
            imported: number;
            /** Format: int32 */
            alreadyExisted: number;
            failed: components["schemas"]["RowErrorResponse"][];
        };
        FileReportResponse: {
            file: string;
            /** Format: int32 */
            applied: number;
            /** Format: int32 */
            matchedByIsrc: number;
            skipped: components["schemas"]["RowErrorResponse"][];
            failed: components["schemas"]["RowErrorResponse"][];
            errorCode: string | null;
            error: string | null;
        };
        IngestMetricsResponse: {
            /** Format: int32 */
            applied: number;
            /** Format: int32 */
            matchedByIsrc: number;
            /** Format: int32 */
            skippedRows: number;
            /** Format: int32 */
            failedRows: number;
            files: components["schemas"]["FileReportResponse"][];
        };
        IngestPlaylistRequest: {
            /** @description Link, URI `spotify:playlist:…` albo samo id playlisty */
            url: string;
        };
        SkippedItemResponse: {
            /** Format: int32 */
            position: number;
            reason: string;
        };
        IngestPlaylistResponse: {
            /** Format: int64 */
            playlistId: number | null;
            spotifyPlaylistId: string;
            name: string;
            /** Format: int32 */
            tracks: number;
            /** Format: int32 */
            imported: number;
            /** Format: int32 */
            alreadyExisted: number;
            skipped: components["schemas"]["SkippedItemResponse"][];
        };
        FailedPlaylistResponse: {
            spotifyPlaylistId: string;
            name: string | null;
            errorCode: string;
            reason: string;
        };
        IngestMyPlaylistsResponse: {
            imported: components["schemas"]["IngestPlaylistResponse"][];
            failed: components["schemas"]["FailedPlaylistResponse"][];
        };
        PlaylistRefreshStatusResponse: {
            outcome: components["schemas"]["RefreshOutcome"];
            /** Format: date-time */
            lastRunAt: string | null;
            /** Format: int32 */
            refreshedPlaylists: number;
            /** Format: int32 */
            failedPlaylists: number;
            message: string | null;
            /** Format: int64 */
            intervalSeconds: number;
        };
        SpotifyAccountResponse: {
            connected: boolean;
            spotifyUserId: string | null;
            displayName: string | null;
            scopes: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            /** Format: date-time */
            connectedAt: string | null;
        };
    };
    responses: {
        /** @description Błąd walidacji */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Zasób nie istnieje */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Konflikt — zasób zmieniony w innym miejscu albo już istnieje */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Zewnętrzne API odmówiło odpowiedzi */
        ExternalServiceError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SpotifyId: string;
        PlaylistId: number;
        PlaylistIdPath: number;
        ExecutionId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchTracks: {
        parameters: {
            query?: {
                search?: string;
                genreFamily?: components["schemas"]["GenreFamily"];
                yearMin?: number;
                yearMax?: number;
                durationMinSec?: number;
                durationMaxSec?: number;
                popularityMin?: number;
                explicit?: boolean;
                bpmMin?: number;
                bpmMax?: number;
                tempoClass?: components["schemas"]["TempoClass"];
                energy?: string;
                /** @description Pozycja koła Camelot, np. `8A` (D25) */
                camelot?: string;
                /** @description Rozszerza filtr o tonacje zgodne (±1 i równoległa) */
                camelotCompatible?: boolean;
                inLibrary?: boolean;
                ratingMin?: number;
                tag?: string;
                valenceMin?: number;
                valenceMax?: number;
                instrumentalMin?: number;
                livenessMax?: number;
                bpmSource?: components["schemas"]["BpmSource"];
                missing?: components["schemas"]["MissingGroup"];
                sort?: components["schemas"]["CatalogSort"];
                direction?: components["schemas"]["SortDirection"];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strona wyniku */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageCatalogRowResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: components["parameters"]["SpotifyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Utwór */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTrackMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: components["parameters"]["SpotifyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metryki utworu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackMetricsResponse"];
                };
            };
            /** @description Utwór nie dostał metryk */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMetricsCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pokrycie metrykami */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsCoverageResponse"];
                };
            };
        };
    };
    listLibraryTracks: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strona wpisów */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageLibraryEntryResponse"];
                };
            };
        };
    };
    addLibraryTrack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLibraryTrackRequest"];
            };
        };
        responses: {
            /** @description Wpis utworzony */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getLibraryTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: components["parameters"]["SpotifyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wpis biblioteczny */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntryResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteLibraryTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: components["parameters"]["SpotifyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usunięto */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateLibraryTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotifyId: components["parameters"]["SpotifyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLibraryEntryRequest"];
            };
        };
        responses: {
            /** @description Wpis po zmianie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getLibraryOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Przegląd */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryOverviewResponse"];
                };
            };
        };
    };
    listLibraryTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista tagów */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    listPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistSummaryResponse"][];
                };
            };
        };
    };
    createPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePlaylistRequest"];
            };
        };
        responses: {
            /** @description Playlista utworzona */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistSummaryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlista ze składem */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deletePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usunięto */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    renamePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePlaylistRequest"];
            };
        };
        responses: {
            /** @description Playlista po zmianie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistSummaryResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    reorderPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderPlaylistRequest"];
            };
        };
        responses: {
            /** @description Playlista po zmianie kolejności */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    addPlaylistTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPlaylistTrackRequest"];
            };
        };
        responses: {
            /** @description Playlista po zmianie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removePlaylistTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PlaylistId"];
                spotifyId: components["parameters"]["SpotifyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlista po zmianie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportPlaylistToSpotify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PlaylistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wynik eksportu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistExportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    proposeSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetProposalRequest"];
            };
        };
        responses: {
            /** @description Propozycja */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetProposalResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    fillSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlistId: components["parameters"]["PlaylistIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetFillRequest"];
            };
        };
        responses: {
            /** @description Dalszy ciąg setu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetFillResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    suggestForSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlistId: components["parameters"]["PlaylistIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSuggestionRequest"];
            };
        };
        responses: {
            /** @description Propozycje */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetSuggestionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    startEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichRequest"];
            };
        };
        responses: {
            /** @description Job wystartował */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionIdResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    estimateEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichRequest"];
            };
        };
        responses: {
            /** @description Szacunek */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentEstimateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listEnrichJobs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historia wykonań */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichJobResponse"][];
                };
            };
        };
    };
    getEnrichJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status wykonania */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichJobResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getEnrichJobFailures: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista pominięć */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichFailureResponse"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    restartEnrichJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nowe wykonanie wystartowało */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionIdResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getMissingCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liczniki braków */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingFieldsCount"];
                };
            };
        };
    };
    ingestFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Raport importu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestFileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    ingestMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    file: string[];
                };
            };
        };
        responses: {
            /** @description Raport per plik */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestMetricsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    ingestPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestPlaylistRequest"];
            };
        };
        responses: {
            /** @description Raport importu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestPlaylistResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            502: components["responses"]["ExternalServiceError"];
        };
    };
    ingestMyPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raport zbiorczy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestMyPlaylistsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getPlaylistRefreshStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status odświeżania */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistRefreshStatusResponse"];
                };
            };
        };
    };
    spotifyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Przekierowanie na stronę zgody */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    spotifyCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Konto połączone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyAccountResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    spotifyStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stan połączenia */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyAccountResponse"];
                };
            };
        };
    };
}
